# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fwWylQLh1fHxIJsrx07p6960asPSlegK
"""

import streamlit as st
import pandas as pd
import joblib
import io

# Titre de l'application
st.set_page_config(page_title="Prédiction Solvabilité Client", layout="centered")
st.title("🔍 Prédiction du Statut de Solvabilité d’un Client")

st.markdown("""
Cette application prédit si un client est **solvable** ou **non solvable** à partir de ses informations financières.
""")

# Chargement des modèles
try:
    model = joblib.load("models/logistic_model.pkl")
    scaler = joblib.load("models/scaler.pkl")
except FileNotFoundError:
    st.error("❌ Modèles non trouvés. Assurez-vous que les fichiers 'logistic_model.pkl' et 'scaler.pkl' existent dans le dossier 'models/'.")
    st.stop()

# Sidebar - Entrée utilisateur
st.sidebar.header("🧾 Informations du client")
age = st.sidebar.number_input("Âge", min_value=18, max_value=100, value=30)
marital = st.sidebar.selectbox("Statut marital", options=[1, 2, 3], format_func=lambda x: {1: "Célibataire", 2: "Marié", 3: "Divorcé"}[x])
expenses = st.sidebar.number_input("Dépenses mensuelles", min_value=0.0, max_value=1000.0, value=200.0)
income = st.sidebar.number_input("Revenu mensuel", min_value=0.0, max_value=2000.0, value=800.0)
amount = st.sidebar.number_input("Montant du crédit demandé", min_value=0.0, max_value=10000.0, value=1000.0)
price = st.sidebar.number_input("Valeur de l’achat", min_value=0.0, max_value=15000.0, value=1200.0)

# Préparation des données
user_data = pd.DataFrame({
    "Age": [age],
    "Marital": [marital],
    "Expenses": [expenses],
    "Income": [income],
    "Amount": [amount],
    "Price": [price]
})

# Affichage des données saisies
st.subheader("📋 Données saisies")
st.write(user_data)

# Bouton de prédiction
if st.sidebar.button("⚙️ Prédire"):
    try:
        user_scaled = scaler.transform(user_data)
        prediction = model.predict(user_scaled)
        proba = model.predict_proba(user_scaled)[:, 1]

        if prediction[0] == 1:
            st.error(f"🔴 Le client est **non solvable** avec une probabilité de {proba[0]:.1%}.")
        else:
            st.success(f"🟢 Le client est **solvable** avec une probabilité de {1 - proba[0]:.1%}.")

        # Téléchargement CSV
        result_df = user_data.copy()
        result_df['Statut Prédit'] = ['Non solvable' if prediction[0] == 1 else 'Solvable']
        result_df['Probabilité (Non Solvable)'] = [f"{proba[0]:.1%}"]

        csv = result_df.to_csv(index=False).encode('utf-8')
        st.download_button(
            label="📥 Télécharger les résultats en CSV",
            data=csv,
            file_name="prediction_client.csv",
            mime='text/csv'
        )

    except Exception as e:
        st.error(f"❌ Une erreur est survenue : {e}")